name: tagyourtaxi_driver
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'



dependency_overrides:
  http: ^0.13.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  flutter_svg: ^2.0.17
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  firebase_messaging: ^15.1.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.0.0
  fluttertoast: ^8.2.8
  permission_handler: ^11.0.1
  share_plus: ^10.1.2
  flutter_stripe: ^11.2.0
  connectivity_plus: ^6.1.0
  image_picker: ^1.1.2
  # google_maps_flutter: ^2.10.1
  yandex_mapkit: ^4.1.0
  geolocator: ^13.0.2
  location: ^8.0.0
  audioplayers: ^6.1.0
  razorpay_flutter: ^1.3.7
  package_info_plus: 4.2.0
  vector_math: ^2.1.1
  awesome_notifications: ^0.10.1
  webview_flutter: ^4.4.1
  flutter_inappwebview: ^6.1.5
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/map_style.json
    - assets/maps_style.json
    - assets/map_style_black.json
